version: "3.8"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mynet

  api:
    build: .
    container_name: api
    restart: on-failure
    ports:
      - "8000:8000"   
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_HOST=${POSTGRES_HOST:-database}

      - API_PORT=${API_PORT:-8000}
      - API_SECRET_KEY=${API_SECRET_KEY:-my-32-character-ultra-secure-and-ultra-long-secret}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE:-30}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME:-admin}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-admin}
    networks:
      - mynet
  
volumes:
  db-data:
  pgadmin-data: 

networks:
  mynet:
    driver: bridge